Nix minimal version: 1.10 -> 1.11
`ruby` attribute requires features from 1.11
```
$ nix-build -A ruby
error: cannot coerce a set to a string, at pkgs/development/interpreters/ruby/default.nix:57:17
```